### ISSUE TITLE
TMC 2209 UART Mode on Ruby

### ISSUE THREAD

**Issue by Joshuananas** [Dtcreation/Firmware-Molise-Artillery#141]
### Describe the feature you want

It would be possible to configure the TMC2209 in UART mode on an X2 with the RUBY using the following ports:
X > PC13
Y > PC14
Z > PC15
E1 > PB6
![h87re4wrbrd91](https://user-images.githubusercontent.com/118482374/202571140-8199bc3c-83f7-4680-9845-f1d1d10bae50.png)
https://www.lesimprimantes3d.fr/forum/topic/48552-sch%C3%A9ma-pinout-artillery-ruby-v12-genius-pro-sidewinder-x2-hornet/
Adding TMC2209 on Ruby includes soldering jumpers on M1 and M2 on all driver sockets.

**Comment by SckyzO** [comment]
Hello @Joshuananas 

The Artillery Ruby board doesn’t support UART and it can not be done from the firmware ... but

To use UART mode, you need to connect diag pin to needest ports on EXP1, and declare new pin in the ruby card pin lib. 

in this file : 
```
Marlin/src/pins/stm32f4/pins_ARTILLERY_RUBY.h
```

```
//
// TMC StallGuard DIAG pins
//
#define X_DIAG_PIN                         PC13 // X-STOP
#define Y_DIAG_PIN                         PC14 // Y-STOP
#define Z_DIAG_PIN                         PC15  // Z-STOP
#define E0_DIAG_PIN                        PB6 // E0DET
```

let me know if it works but I can't add this to Molise because Molise modify only configuration.h and configuration_avh.h

Regards,
